dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: "Tests"
      name: "Unit tests"
      script: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - name: "E2E tests"
      script: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
    - stage: "Build prod"
      script: npm run build
